spring:
  application:
      name: eomo-monitor
    profiles:
      active: dev
    cloud:
      config:
        fail-fast: true
        discovery:
          service-id: eomo-config
          enabled: true
        profile: ${spring.profiles.active}
        label: ${spring.profiles.active}
  ---
  spring:
    profiles: dev
  eureka:
    instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 20
    client:
      serviceUrl:
        defaultZone: http://pig:gip6666@localhost:1025/eureka
      registry-fetch-interval-seconds: 10

  ---
  spring:
    profiles: prod
  eureka:
    instance:
      prefer-ip-address: true
    client:
      serviceUrl:
        defaultZone: http://pig:gip6666@eureka:1025/eureka

  elasticjob:
    #注册中心配置
    zookeeper:
      server-lists: 127.0.0.1:6181
      namespace: eomo-monitor
    #简单作业配置
    simples:
      #spring简单作业示例配置
      spring-simple-job:
        #配置简单作业，必须实现com.dangdang.ddframe.job.api.simple.SimpleJob
        job-class: com.prato.cloud.daemon.job.SpringSimpleJob
        cron: 0/2 * * * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=Beijing,1=Shanghai,2=Guangzhou
        #配置监听器
        listener:
          #配置每台作业节点均执行的监听，必须实现com.dangdang.ddframe.job.lite.api.listener.ElasticJobListener
          listener-class: ElasticJobListener
    #流式作业配置
    dataflows:
      #spring简单作业示例配置
      spring-dataflow-job:
        #配置简单作业，必须实现com.dangdang.ddframe.job.api.dataflow.DataflowJob<T>
        job-class: com.prato.cloud.daemon.job.SpringDataflowJob
        cron: 0/2 * * * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=Beijing,1=Shanghai,2=Guangzhou
        streaming-process: true
        #配置监听器
        listener:
          #配置分布式场景中仅单一节点执行的监听，必须实现com.dangdang.ddframe.job.lite.api.listener.AbstractDistributeOnceElasticJobListener
          distributed-listener-class: DistributeElasticJobListener
          started-timeout-milliseconds: 5000
          completed-timeout-milliseconds: 10000
    #脚本作业配置
    scripts:
      #脚本作业示例配置
      script-job:
        cron: 0/2 * * * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=Beijing,1=Shanghai,2=Guangzhou
        script-command-line: youPath/spring-boot-starter-demo/elastic-job-spring-boot-starter-demo/src/main/resources/script/demo.bat